### ISSUE TITLE
Few questions 

### ISSUE THREAD

**Issue by pnhearer** [jiegec/netconf-rs#2]
Are you still working on this library?

Are you interested in bringing this crate up to RFC 2642 compliance?

Are you interested in getting commits against other hardware? 

Im looking to contribute for:

- Cisco
- Arista
- Dell
- Juniper 

platforms.

**Comment by jiegec** [comment]
> Are you still working on this library?

Yes, maintained.
> 
> Are you interested in bringing this crate up to RFC 2642 compliance?
> 

Nope.

> Are you interested in getting commits against other hardware?

Yes, pull requests are welcome.

> 
> Im looking to contribute for:
> 
>     * Cisco
> 
>     * Arista
> 
>     * Dell
> 
>     * Juniper
> 
> 
> platforms.

**Comment by pnhearer** [comment]
That sounds good. May i inquire as to why there is no interest in RFC 2642 support?

**Comment by jiegec** [comment]
> That sounds good. May i inquire as to why there is no interest in RFC 2642 support?

The library was used by me to modifying the vlan configuration of a H3C switch, and that's all.

**Comment by jiegec** [comment]
By the way, RFC 2642 is `Cabletron's VLS Protocol Specification`, is it related to NETCONF?

**Comment by pnhearer** [comment]
I understand. Ok! Looking forward to working with you.
