### ISSUE TITLE
Philosophical question

### ISSUE THREAD

**Issue by pnhearer** [jiegec/netconf-rs#9]
So, i want to ask. Whats your vision here for this crate. Are you wanting to be the one stop shop for everything netconf server. Or are you looking to provide vendor support. Here's why I ask. This exists, and its pretty amazing.

https://github.com/YangModels/yang

If we are looking to pull this in too. We can have vendor support for free.

Netconf is one of those server models that are a bit convoluted, but if you follow the dichotomy. The server is the vendor supported device, so providing vendor support is providing server support.

**Comment by jiegec** [comment]
> So, i want to ask. Whats your vision here for this crate. Are you wanting to be the one stop shop for everything netconf server. Or are you looking to provide vendor support. Here's why I ask. This exists, and its pretty amazing.
> 
> https://github.com/YangModels/yang
> 
> If we are looking to pull this in too. We can have vendor support for free.
> 
> Netconf is one of those server models that are a bit convoluted, but if you follow the dichotomy. The server is the vendor supported device, so providing vendor support is providing server support.

I have invited you as collaborator. You can make any decision, as long as I can use this library to configure vlan interface of my H3C switch.

**Comment by pnhearer** [comment]
You got it boss!
